---
# vars file for master_node
access_key: ********************
secret_key: *******************************


pkg: iproute-tc

k8s_repo_pkg:
  - kubeadm
  - kubectl
  - kubelet

docker_svc: docker

ports:
- "6443/tcp"
- "10250/tcp"

flannel_url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

