---
# defaults file for worker_node

- name: Disabling swap 
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(.*swap*)'
    replace: '#\1'

- name: Configuring yum repo for k8s master node
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install iproute-tc
  yum:
    name: "{{ pkg }}"
    state: present

- name: Installing firewalld
  package:
    name:
      - firewalld
    state: present

- name: Giving --no-best option
  replace:
    path: "/etc/dnf/dnf.conf"
    regexp: "True"
    after: "best="
    replace: "False"

- name: Get dnf
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  command: dnf install docker-ce --nobest -y

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Install kubeadm, kubelet, and kubectl
  yum: 
    name: "{{ k8s_repo_pkg }}"
    state: present
  register: kubeadm

- name: Start Kubelet
  service:
    name: kubelet
    state: started
    enabled: true

- name: Updating docker cgroup on worker node
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restart Docker service
  service: 
    name: "{{ docker_svc }}"
    state: restarted

- name: Starting firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Allow Network ports in Firewalld
  firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ ports }}"

- name: Joining slaves with the master
  command: "{{ hostvars[groups['master_node'][0]]['output']['stdout'] }}"

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches