---
# vars file for worker_node
# vars file for worker_node

services:
  - kubelet

pkg: iproute-tc

k8s_repo_pkg:
  - kubeadm
  - kubectl
  - kubelet

docker_svc: docker

ports:
- "6443/tcp"
- "10250/tcp"
